# Generated by Django 5.2.4 on 2025-07-30 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destinatie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tara', models.CharField(max_length=100)),
                ('oras', models.CharField(max_length=100)),
                ('descriere', models.TextField()),
                ('imagine', models.ImageField(upload_to='destinatii/')),
            ],
        ),
        migrations.CreateModel(
            name='PachetTuristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=100)),
                ('pret', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_start', models.DateField()),
                ('data_sfarsit', models.DateField()),
                ('locuri_disponibile', models.IntegerField()),
                ('destinatie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferte.destinatie')),
            ],
        ),
        migrations.CreateModel(
            name='Rezervare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume_client', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefon', models.CharField(max_length=20)),
                ('data_rezervare', models.DateTimeField(auto_now_add=True)),
                ('numar_persoane', models.PositiveIntegerField()),
                ('pachet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oferte.pachetturistic')),
            ],
        ),
    ]
