# Generated by Django 5.2.4 on 2025-07-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferte', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titlu', models.CharField(max_length=100)),
                ('descriere', models.TextField()),
                ('pret', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
