# Generated by Django 5.2.4 on 2025-08-01 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferte', '0002_oferta'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='imagine',
            field=models.ImageField(blank=True, null=True, upload_to='oferte/'),
        ),
    ]
