# Generated by Django 5.2.4 on 2025-08-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferte', '0003_oferta_imagine'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta',
            name='destinatie',
            field=models.CharField(default='Necunoscut', max_length=255),
        ),
        migrations.AddField(
            model_name='oferta',
            name='disponibilitate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='oferta',
            name='durata',
            field=models.CharField(default='1 zi', max_length=50),
        ),
        migrations.AddField(
            model_name='oferta',
            name='facilitati',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='numar_locuri',
            field=models.IntegerField(default=20),
        ),
        migrations.AddField(
            model_name='oferta',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='oferta',
            name='tip_cazare',
            field=models.CharField(default='Hotel', max_length=100),
        ),
        migrations.AddField(
            model_name='oferta',
            name='transport',
            field=models.CharField(default='Autocar', max_length=100),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='titlu',
            field=models.CharField(max_length=255),
        ),
    ]
